theme: minima
title: My Blog
author: jonathanchan6
email: 1155142863@link.cuhk.edu.hj
description: > # this means to ignore newlines until "baseurl:"
  Yo! Welcome xd

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
